apiVersion: v1
data:
  fluent.conf: |-
    <source>
      @type tcp
      tag sensor.tcp
      port "#{ENV['FLUENT_TCP_PORT']}"
      format none
    </source>

    <match **>
      @type file
      path /fluentd/data/test
    </match>
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-15T01:26:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:fluent.conf: {}
    manager: kubectl-create
    operation: Update
    time: "2020-12-15T01:26:13Z"
  name: fluentd-config
  namespace: default
  resourceVersion: "29007"
  selfLink: /api/v1/namespaces/default/configmaps/fluent-conf-configmap
  uid: 3896ddc3-8392-4151-adee-d6c76558fe5a